#!/bin/sh
COMMIT_MESSAGE="v";
PREFIX="<!--LAST_COMMIT: ";
POSTFIX="-->";
ENABLED=1;
# git config core.hooksPath hooks
echo "Running pre-push hook";

# define the file where commit info will be saved
file=src/main/webapp/index.html;

# don't modify!
branch=$(git rev-parse --abbrev-ref HEAD);
if [[ $branch == master ]] || [[  $(git log -1 --format='%s') == $COMMIT_MESSAGE ]] || [[ ! $ENABLED == 1 ]];
    then exit 0;
else
    USER=$(git config user.name);
    DATE=$(date +%Y-%m-%d\ %H:%M:%S);
    tag=$PREFIX${USER:0:7}" "$DATE$POSTFIX;

    if grep -q "$PREFIX" $file
    then
        sed -i -e "s/$PREFIX.*/$tag/g" $file;
    else
        echo $tag >> $file;
    fi

    git commit $file -m "$COMMIT_MESSAGE";
    echo "last version was commited. Invoke push again!"
    exit 1;
fi

