#!/bin/sh
# git config core.hooksPath hooks
echo "Running pre-commit hook";

# define the file where commit info will be saved
file=src/main/webapp/index.html;

# don't modify!
prefix="<!--COMMIT: ";
prefixAuthor=$prefix$(git config user.name);
tag=$prefixAuthor" "$(date +%Y-%m-%d\ %H:%M:%S);

if grep -q "$prefixAuthor" $file
then
    sed -i -e "s/$prefixAuthor.*/$tag/g" $file;
else
    echo $tag >> $file;
fi

branch=$(git rev-parse --abbrev-ref HEAD);
if [[ $branch == master ]]
then
    sed -i -e "s/$prefix.*//g" $file;
fi

git add $file;


