#!/bin/sh
COMMENT="v";
PREFIX="<!--LAST_COMMIT: ";
ENABLED=1;
# git config core.hooksPath hooks
echo "Running pre-push hook";

# define the file where commit info will be saved
file=src/main/webapp/index.html;

# don't modify!
if [[  $(git log -1 --format='%s') == $COMMENT ]] || [[ ! $ENABLED == 1 ]];
    then exit 0;
else
    tag=$PREFIX$(git config user.name)" "$(date +%Y-%m-%d\ %H:%M:%S)"-->";

    if grep -q "$PREFIX" $file
    then
        sed -i -e "s/$PREFIX.*/$tag/g" $file;
    else
        echo $tag >> $file;
    fi

    branch=$(git rev-parse --abbrev-ref HEAD);
    if [[ $branch == master ]]
    then
        sed -i -e "s/$PREFIX.*//g" $file;
    fi

    git commit $file -m "$COMMENT";
    echo "last version was commited. Invoke push again!"
    exit 1;
fi

