#!/bin/sh
# git config core.hooksPath hooks
echo "Running pre-commit hook";

COMMENT="last commit version";
lastCommit=$(git log -1 --format='%s');
if [[  $lastCommit == $COMMENT ]];
then echo "var is unset";
else echo "var is set to '$var'";
fi
